// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --------- //
// blink_led //
// --------- //

#define blink_led_wrap_target 0
#define blink_led_wrap 2

static const uint16_t blink_led_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block                      
    0x6001, //  1: out    pins, 1                    
    0x0000, //  2: jmp    0                          
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program blink_led_program = {
    .instructions = blink_led_program_instructions,
    .length = 3,
    .origin = -1,
};

static inline pio_sm_config blink_led_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + blink_led_wrap_target, offset + blink_led_wrap);
    return c;
}
#endif

